## 1.

a. Target variable: sales

b. sales = $\beta _{1}$ * reviews score + $\beta _{2}$ *frequency of 'bad' + $\beta _{3}$ *frequency of 'good' + $\beta _{4}$ *frequency of 'doesn't work'

c. For scores range from 1 to 10. Divide them by 10 and then multiply by 5.

d. map : good to 5. bad to 1. For reviews without numeric rating, apply a sentimental analysis 

e. (b)

## 2.

y = $\beta _{1}$ * $x _{i1}$ + $\beta _{2}$ * $x _{i2}$ + b 

In [3]:
import pandas as pd
from sklearn.linear_model import LinearRegression

In [5]:
q2 = pd.DataFrame(data = {'x_1':[0,0,1,1], 'x_2':[0,1,0,1], 'y':[1,4,3,7]})

In [6]:
q2

x_1  x_2  y
0    0    0  1
1    0    1  4
2    1    0  3
3    1    1  7

In [10]:
LinearRegression().fit(q2[['x_1','x_2']],q2['y']).coef_

array([ 2.5,  3.5])

In [11]:
LinearRegression().fit(q2[['x_1','x_2']],q2['y']).intercept_

0.75000000000000044

y = 2.5 * $x _{i1}$ + 3.5 * $x _{i2}$ + 0.75

## 3.

a.

$\beta _{1}$ =  $a _{1}$
 
$\beta _{2}$ =  $a _{2}$

$\phi(x_{1}, x_{2}) = [x_{1} e^{-x_{1}-x_{2}}, x_{2} e^{-x_{1}-x_{2}} ]$

b. 
Two binary features: 

$x < 1, \phi_{1} = 1, \phi_{2} = 0$

$x \geq 1, \phi_{1} = 0, \phi_{2} = 1$

$\beta _{1}$ =  $\phi _{1}a_{1} + \phi_{2}a_{3}$
 
$\beta _{2}$ =  $\phi _{1}a_{2} + \phi_{2}a_{4}$

$ a_{1} = \frac{\beta_{1}-\phi_{2} a_{3}} {\phi_{1}} $
...


$\phi(x) = [1, x]$



c. 

$\beta _{1}$ =  $e^{a_{2}}$
 
$\beta _{2}$ =  $a_{1}e^{a_{2}}$


$\phi(x_{1}, x_{2})= [e^{-x_{2}}, x_{1}e^{-x_{2}}]$

## 4.

$\beta =[a_{1}, a_{2}...a_{M}, b_{0}, b_{1}...,b{N}]^{T}$

M + N + 1 parameters

b.

$  A = \left [ y_{k-1}, y_{k-2}, ...y_{k-M}, x_{k}, x_{k-1},...x_{k-N} \right ]$

c.



## 5.

a.

$ x_{k} = cos^{m}ksin^{\Omega _{l}-m}k $

$\beta_{l} = a_{l}\sum_{m=0}^{\Omega _{l}}\binom{\Omega }{m}cos[\frac{1}{2}(\Omega _{l}-m)\pi ]+b_{l}\sum_{m=0}^{\Omega _{l}}\binom{\Omega }{m}sin[\frac{1}{2}(\Omega _{l}-m)\pi ]$

b. it would not be a nonlinear problem. 

## 6.

## a.

In [150]:
import numpy as np

In [220]:
n = 3
p = 3
X = np.random.randn(n,p)
beta = np.random.randn(p,1)

In [221]:
X

array([[-0.72040513,  0.05765048,  0.84692716],
       [-0.57428663,  0.42413205, -1.02341032],
       [ 1.23488009,  0.87161547, -1.11317551]])

In [222]:
n = X.shape[0]
yhat = np.zeros(n)
for i in range(n):
    yhat[i] = beta[0] * X[i,0] + beta[1] * X[i,1] + beta[2] * X[i, 1] * X[i,2]

In [223]:
yhat

array([-0.1241082 ,  0.86901518,  2.28120622])

## Rewrite without for loop:

In [224]:
X_2 = np.array([X[:,0], X[:,1], X[:,1] * X[:,2]])

In [225]:
X_2.T

array([[-0.72040513,  0.05765048,  0.04882575],
       [-0.57428663,  0.42413205, -0.43406111],
       [ 1.23488009,  0.87161547, -0.970261  ]])

In [226]:
np.dot(X_2.T,beta)

array([[-0.1241082 ],
       [ 0.86901518],
       [ 2.28120622]])

# b.

## Rewrite the code:

In [306]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [307]:
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [308]:
alpha = np.random.randn(3,1)

In [309]:
beta = np.random.randn(3,1)

In [310]:
beta

array([[-0.76891509],
       [ 0.98752512],
       [-0.47577669]])

In [311]:
alpha * np.exp(beta * X)

array([[ -2.18291228e-01,  -1.01181404e-01,  -4.68991660e-02],
       [  5.04496711e+01,   1.35436291e+02,   3.63589859e+02],
       [  1.05299146e-02,   6.54331246e-03,   4.06602898e-03]])

## C.

## Original

In [326]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [328]:
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [329]:
n,d = X.shape
m,d = Y.shape
dist = np.zeros((n,m))
for i in range(n):
    for j in range(m):
        for k in range(d):
            dist[i,j] += (X[i,k] - Y[j,k]) **2

In [339]:
dist

array([[   0.,   27.,  108.],
       [  27.,    0.,   27.],
       [ 108.,   27.,    0.]])

## Rewrite

In [337]:
DXY = X[:,None,:] - Y[None,:,:]
d = np.sum(DXY **2,axis = 2)

In [338]:
d

array([[  0,  27, 108],
       [ 27,   0,  27],
       [108,  27,   0]])